/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

/**
 *
 * @author User
 */
public class FrameDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FrameDashboard
     */
    public FrameDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnProduk = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnGamification = new javax.swing.JButton();
        btnKategori = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnDetail = new javax.swing.JButton();
        btnLeaderboard = new javax.swing.JButton();
        btnReward = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnBadge = new javax.swing.JButton();
        btnChallenge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DASHBOARD");
        jPanel1.add(jLabel1);

        btnProduk.setText("FORM PRODUK");
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });
        jPanel2.add(btnProduk);

        btnUser.setText("FORM USER");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnUser);

        btnTransaksi.setText("FORM TRANSAKSI");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel2.add(btnTransaksi);

        btnGamification.setText("FORM GAMIFICATION");
        btnGamification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGamificationActionPerformed(evt);
            }
        });
        jPanel3.add(btnGamification);

        btnKategori.setText("FORM KATEGORI");
        btnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriActionPerformed(evt);
            }
        });
        jPanel3.add(btnKategori);

        btnPoint.setText("FORM POINT");
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });
        jPanel3.add(btnPoint);

        btnDetail.setText("FORM DETAIL TRANSAKSI");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });
        jPanel4.add(btnDetail);

        btnLeaderboard.setText("FORM LEADERBOARD");
        btnLeaderboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaderboardActionPerformed(evt);
            }
        });
        jPanel4.add(btnLeaderboard);

        btnReward.setText("FORM REWARD");
        btnReward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRewardActionPerformed(evt);
            }
        });
        jPanel4.add(btnReward);

        btnBadge.setText("FORM BADGE");
        btnBadge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBadgeActionPerformed(evt);
            }
        });
        jPanel5.add(btnBadge);

        btnChallenge.setText("FORM CHALLENGE");
        btnChallenge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChallengeActionPerformed(evt);
            }
        });
        jPanel5.add(btnChallenge);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        // TODO add your handling code here:
    FrameProduk frameProduk = new FrameProduk(); 
    frameProduk.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
    FrameUser frameUser = new FrameUser(); 
    frameUser.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
    FrameTransaksi frameTransaksi = new FrameTransaksi(); 
    frameTransaksi.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriActionPerformed
        // TODO add your handling code here:
    FrameKategori frameKategori = new FrameKategori(); 
    frameKategori.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_btnKategoriActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
    FrameTransaksiDetail frameDetail = new FrameTransaksiDetail(); 
    frameDetail.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnLeaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaderboardActionPerformed
        // TODO add your handling code here:
    FrameLeaderboard frameLeaderboard = new FrameLeaderboard(); 
    frameLeaderboard.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnLeaderboardActionPerformed

    private void btnGamificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGamificationActionPerformed
        // TODO add your handling code here:
    FrameGamification frameGamification = new FrameGamification(); 
    frameGamification.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnGamificationActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        // TODO add your handling code here:
    FramePoint framePoint = new FramePoint(); 
    framePoint.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnBadgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBadgeActionPerformed
        // TODO add your handling code here:
    FrameBadge frameBadge = new FrameBadge(); 
    frameBadge.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBadgeActionPerformed

    private void btnRewardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRewardActionPerformed
        // TODO add your handling code here:
    FrameReward frameReward = new FrameReward(); 
    frameReward.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRewardActionPerformed

    private void btnChallengeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChallengeActionPerformed
        // TODO add your handling code here:
    FrameChallenge frameChallenge = new FrameChallenge(); 
    frameChallenge.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnChallengeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBadge;
    private javax.swing.JButton btnChallenge;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnGamification;
    private javax.swing.JButton btnKategori;
    private javax.swing.JButton btnLeaderboard;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnReward;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
